[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tock-registers = "*"
aarch64-cpu = "*"
linked_list_allocator = "*"

[features]
bsp_rpi3 = []